version: '3.2'
services:
    jenkins:
        container_name: jenkins
        ports:
            - '8080:8080'
            - '50000:50000'
        image: ptorrezao/jenkins
        build:
            context: ./master
        volumes:
            - type: volume
              source: jenkins_home
              target: /var/jenkins_home
    jenkins-slave:
        container_name: jenkins-slave
        build:
            context: ./slave
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        image: ptorrezao/jenkins-slave
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
        depends_on:
            - jenkins
        deploy:
            replicas: 3

volumes:
  jenkins_home: